Variablize naked -tv-exit-on-error

diff --git a/scripts/opt-alive.sh.in b/scripts/opt-alive.sh.in
--- a/scripts/opt-alive.sh.in
+++ b/scripts/opt-alive.sh.in
@@ -83,13 +83,15 @@ if [[ $SKIP_TV == 0 && $NPM_TV == 1 ]]; then
   NPM_PLUGIN="-load-pass-plugin=@CMAKE_BINARY_DIR@/tv/$TV_SHAREDLIB"
 fi
 
-COMMAND="$TIMEOUT @LLVM_BINARY_DIR@/bin/opt -load=@CMAKE_BINARY_DIR@/tv/$TV_SHAREDLIB  $NPM_PLUGIN -tv-exit-on-error $TV $OPT_ARGS $TV $TV_SMT_TO $TV_REPORT_DIR $TV_SMT_STATS"
+TV_EXIT_ON_ERROR="-tv-exit-on-error"
+
+COMMAND="$TIMEOUT @LLVM_BINARY_DIR@/bin/opt -load=@CMAKE_BINARY_DIR@/tv/$TV_SHAREDLIB  $NPM_PLUGIN $TV_EXIT_ON_ERROR $TV $OPT_ARGS $TV $TV_SMT_TO $TV_REPORT_DIR $TV_SMT_STATS"
 
 if [[ $VERBOSE == 1 ]]; then
   echo COMMAND: $COMMAND >&2
   echo >&2
-  echo '$TV_SHAREDLIB, $NPM_PLUGIN, $TV, $OPT_ARGS, $TV, $TV_SMT_TO, $TV_REPORT_DIR, $TV_SMT_STATS:' >&2
-  echo "$TV_SHAREDLIB, $NPM_PLUGIN, $TV, $OPT_ARGS, $TV, $TV_SMT_TO, $TV_REPORT_DIR, $TV_SMT_STATS" >&2
+  echo '$TV_SHAREDLIB, $NPM_PLUGIN, $TV_EXIT_ON_ERROR, $TV, $OPT_ARGS, $TV, $TV_SMT_TO, $TV_REPORT_DIR, $TV_SMT_STATS:' >&2
+  echo "$TV_SHAREDLIB, $NPM_PLUGIN, $TV_EXIT_ON_ERROR, $TV, $OPT_ARGS, $TV, $TV_SMT_TO, $TV_REPORT_DIR, $TV_SMT_STATS" >&2
   echo >&2
 fi
 
